Completed typescript-conditionals exercise - Shea Pone
SheaPone/m1-0724-code-solutions pull request #11
Opened 2024-07-17 04:30 UTC by SheaPone

![Screenshot 2024-07-16 at 9 28 03 PM (2)](https://github.com/user-attachments/assets/bd041ea0-277c-429a-ad1d-dc718c0bf5c6)

2024-07-17 18:45 UTC, hesam commented on typescript-conditionals/main.ts
> +  if (person.age >= 0) {
they want you to use AND operator for the two conditions (drinking and driving).

2024-07-17 18:47 UTC, hesam requested changes
See comment in code

2024-07-18 02:24 UTC, SheaPone commented
<img width="661" alt="Screenshot 2024-07-17 at 7 22 15 PM" src="https://github.com/user-attachments/assets/ffa0c175-eba9-4420-b0ad-f2365b74edd5">

2024-07-18 02:57 UTC, hesam approved these changes
Great!

2024-07-18 03:26 UTC, merged