Completed typescript-data-model exercise - Shea Pone
SheaPone/m1-0724-code-solutions pull request #7
Opened 2024-07-12 05:10 UTC by SheaPone

![typescript-data-model](https://github.com/user-attachments/assets/034cdcf8-033e-4d62-90fc-65348c45a9a5)

2024-07-12 21:18 UTC, hesam requested changes
Great so far. 

- Can you work it out so each order uses an array to represent all items purchased in it? That would be superior and flexible to using an optional 'secondPartofOrder'  property?

2024-07-13 02:43 UTC, SheaPone commented
<img width="1512" alt="Screenshot 2024-07-12 at 7 40 52 PM" src="https://github.com/user-attachments/assets/c2819dc2-0739-4eda-8981-c14fd700b15d">

2024-07-14 00:06 UTC, hesam commented on typescript-data-model/order-history.ts
> +interface amazonItem {
By convention user defined types/interfaces should be capitalized (as opposed to primitive types). So I'd go with: AmazonItem

2024-07-14 00:08 UTC, hesam approved these changes
Great all around!

2024-07-15 03:53 UTC, merged